### ISSUE TITLE
decoding issue 

### ISSUE THREAD

**Issue by ad34** [minrk/umsgpack#4]
I'm using umsgpack to send msgpack message over the network to a node.js server (websocket) and I have   one  issue : 

While decoding the message on node.js side the strings are decoded as Buffer. the issue is not happening with the package msgpack-python  (however I cannot use it because of another issue..) , is there an option to change this ?

**Comment by minrk** [comment]
What Python and msgpack-python versions? Can you show a sample of how you are building the message?

**Comment by minrk** [comment]
umsgpack only does two things, both of which ensure that the distinction between bytestrings and text objects is preserved. `msgpack-python`'s defaults deserialize text into bytes and serialize bytes into text by default.

The two things it does:

1. set `encoding='utf-8'` by default in `unpackb`. This ensures that text strings in messages are decoded as Python text objects (unicode on py2, str on py3)
2. set `use_bin_type=True` by default in `packb`. This ensures that bytestrings are treated as binary, and text objects must be used for text.

I suspect that what you are running into is that the `str` object on Python 2 is actually a bytestring, and thus serialized to the msgpack binary type instead of the msgpack text type. On Python 2 you must use unicode strings for text with umsgpack. Or use Python 3, where `str` is a proper text type.

**Comment by ad34** [comment]
python 2.7.12 and msgpacku-0.2.0

this is strange because the code was running fine some weeks ago , still investigating

**Comment by ad34** [comment]
using this solve the issue with strings : 

def encodeMsg(msg):
    return msgpacku.packb(msg,use_bin_type=False)


but I m experiencing the same issue that with msgpack-python : nested msgpack object cannot be decoded

exemple of nested object : 

data =  { "State" : 0x1,"MatchID"     : matchId,"SessionID"   : self.user.sessionID }
msg = { "route" : "SessionState", "data" :  encodeMsg(data) }

about unicode strings, using u before quotes dont change the format. still a buffer on node.js side

ex : 

python : 
 msg = {
                "route" : u"UpdateSession",
                "sessionDesc" : sessions[self.user.sessionID]["sessionDesc"]
            }


node.js 

decrypted.route instanceof Buffer
> true

**Comment by minrk** [comment]
Note that `use_bin_type=False` produces ambiguous results, where both `bytes` and `str` objects will be serialized to the same thing.

A nested msgpack message packed with packb *should* be a binary buffer, because msgpack doesn't produce text, it produces a binary serialization. But it doesn't make a lot of sense to double-serialize your messages. Do you mean to serialize data into msg and then serialize it again when you send `msg`? Why not pass `data` itself in msg and only serialize the final message instead of double-serializing it?

**Comment by ad34** [comment]
yes, I know double serializing msgpack is not efficient, but unfortunalety on the project I have to deal with this , the data is generated as is from a c++ program ( some part of the data is already packed in msgpack and we include it into another msgpack object as binary data ) 

I dont have the issue from c++ to node.js or from node.js to node.js , only from python to node.js (load testing agent)

**Comment by minrk** [comment]
is it included as binary data, or as text? What type do your other programs use to encode the inner message?

**Comment by ad34** [comment]
exemple from node.js to node.js, the nested object is received a binary buffer , but successfully decode as object  : 

const msg = 
        {
            route : "SessionState" ,
            data : msgPackEncode( {State : State,MatchID : matchId,SessionID : sessionId})
        }

websocket.send( msgPackEncode(msg))

**Comment by minrk** [comment]
Gotcha. Assuming you are using [this msgpack](https://www.npmjs.com/package/msgpack), it looks like it behaves the same as `umsgpack`, which is to say that `use_bin_type=True`. But note that you must use *Python text objects* for text, which is `unicode` on Python 2 and `str` on Python 3. If you are stuck on Python 2, this means making sure that you *never* use the native `str` object when you want text. The following scripts do nested encoding and produce the same output in node.js and Python 2. The results are the same on Python 3, but the printout is different.

Python 2:

```python
from __future__ import print_function

import umsgpack as msgpack
o = {u'a': u'b'}
b = msgpack.packb(o)
o2 = {u'x': b}
b2 = msgpack.packb(o2)

for c in b:
    print('%x' % ord(c), end=' ')
print()

for c in b2:
    print('%x' % ord(c), end=' ')
print()
```

javascript:

```javascript
var msgpack = require('msgpack');

var o = {"a": "b"};
var b = msgpack.pack(o);
var o2 = {"x": b};
var b2 = msgpack.pack(o2);
console.log(Array.prototype.map.call(b, n => n.toString(16)).join(' '))
console.log(Array.prototype.map.call(b2, n => n.toString(16)).join(' '))
```

**Comment by ad34** [comment]
Thanks , you are right using unicode  on each string fixed the issue !
